# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
use_frameworks!

target 'Chinook_Example' do

  # Pods for Chinook
  pod 'Chinook', :path => '../'

  target 'Chinook_Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
