# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'chinook_Example' do

  # Pods for Chinook
  pod 'chinook', :path => '../'

  target 'chinook_Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
